[package]
name = "necronux"
version = "0.1.0"
authors = ["Nayan (NayanTheSpaceGuy) <nayantsg@proton.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.13", features = ["derive", "cargo"] }
