name: 'Branch Protection to Main'

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PRs are only from allowed branches
        run: |
          if ! [[ ${GITHUB_HEAD_REF} =~ ^(release/|hotfix/).+ ]]; then
            echo "Error: Pull requests to main can only be from 'release/*' or 'hotfix/*' branches."
            exit 1
          fi
